version: '3'
services:
  student-app:
    container_name: "student"
    build: ./student-app
    ports:
      - "8080:8080"
    depends_on:
      - database
  student-app-client:
    container_name: "client"
    build: ./student-client-app
    ports:
      - "8090:8090"
    depends_on:
      - student-app
  database:
    container_name: "database"
    image: mysql
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentdb
      MYSQL_USER: user
    ports:
      - "3306:3306"
    restart: always